questions/urls.py
from django.urls import path

from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('highscore/', views.highscore, name='high_score'),
    path('login/', views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path("take_quiz/", views.take_quiz, name="take_quiz"),
    path("validate_quiz/", views.validate_quiz, name="validate_quiz"),
]

trivia/urls.py
from django.contrib import admin
from django.urls import path, include
from questions import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')),
]

questions/models.py
from django.db import models


class ResModel(models.Model):
    correct = models.IntegerField()
    incorrect = models.IntegerField()
    total_answered = models.IntegerField()
    total_questions = models.IntegerField()
    score = models.FloatField()
    user = models.CharField(max_length=30, default=None)
    def __str__(self):
        return 'result'

questions/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

questions/views.py
import csv
import random

from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect
from django.shortcuts import render
from .models import ResModel

from .forms import NewUserForm


def get_questions():
    with open('data/questions.csv', mode='r', encoding="utf8") as csv_file:
        csv_reader = csv.DictReader(csv_file)
        return list(csv_reader)


QUESTIONS = get_questions()
QUIZ_LENGTH = 10


def home(request):
    return render(request, 'home.html')


def highscore(request):
    results = ResModel.objects.order_by('score').reverse()
    return render(request, 'questions/highscores.html', {'results': results})


def take_quiz(request):
    random_questions = random.choices(QUESTIONS, k=QUIZ_LENGTH)
    return render(request, 'questions/quiz.html', {'questions': random_questions})


def validate_quiz(request):
    print(request.POST)

    correct_questions = 0
    incorrect_questions = 0
    total_questions = 0

    for question_id, selected_result in request.POST.items():
        try:
            index = int(question_id)
        except ValueError:
            continue
        else:
            total_questions += 1

            if QUESTIONS[index]['correct_answer'] == selected_result:
                correct_questions += 1
            else:
                incorrect_questions += 1

    score = round(float(correct_questions) / QUIZ_LENGTH * 100, 2)

    result = {
            'correct': correct_questions,
            'incorrect': incorrect_questions,
            'total_answered': total_questions,
            'total_questions': QUIZ_LENGTH,
            'score': score,
            'user': request.user
        }
    ResModel(**result).save()
    return render(request, 'questions/result.html', {
        'result': result
    })


def register(request):
    message, error = None, None
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            register(request)
            message = "Registration successful."
            messages.success(request, message)
            return redirect("/questions/login/")
        error = "Unsuccessful registration. Invalid information."
        messages.error(request, error)
        return render(request=request, template_name="questions/register.html", context={
            "register_form": form,
            "error": error,
            "message": message
        })
    else:
        form = NewUserForm()
        return render(request=request, template_name="questions/register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("home")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            error = "Invalid username or password."
            messages.error(request, error)
            return render(request=request, template_name="questions/login.html", context={
                "login_form": AuthenticationForm(), 'error': error
            })

    form = AuthenticationForm()
    return render(request=request, template_name="questions/login.html", context={"login_form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("home")

trivia/views.py
from django.http import HttpResponse


def home(request):
    # remove these print statements later
    print('\n\nRequest object:', request)
    print('Request object type:', type(request), '\n\n')

    html_tags = '''
    <h1>Test your knowledge with us!</h1>
    <h3>Are you ready?</h3>
        <button type="button" class="btn btn-primary">Primary</button>
    '''

    response = HttpResponse(html_tags)
    # remove these print statements later
    print('Response object:', response)
    print('Response object type:', type(response))
    print('\n\nUser-agent info :', end='')
    print(request.META['HTTP_USER_AGENT'], '\n\n')

    return response


def register_request(request):
    # remove these print statements later
    print('\n\nRequest object:', request)
    print('Request object type:', type(request), '\n\n')

    html_tags = '''
    <h1>Test your knowledge with us!</h1>
    <h3>Are you ready?</h3>
    <p>Categories for you:</p>
    <ul>
      <li>Geography</li>
      <li>History</li>
      <li>Science</li>
    </ul>'''

    response = HttpResponse(html_tags)
    # remove these print statements later
    print('Response object:', response)
    print('Response object type:', type(response))
    print('\n\nUser-agent info :', end='')
    print(request.META['HTTP_USER_AGENT'], '\n\n')

    return response

questions/templates/questions/highscores.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Highscores</title>
</head>
<body>
{% block content %}

<table class="table text-center">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Score</th>
      <th scope="col">Number correct</th>
    <th scope="col">Number incorrect</th>
    </tr>
  </thead>
  <tbody>
  {% for result in results %}
      <tr>
      <th scope="row">{{ forloop.counter0 }}</th>
      <td>{{ result.user }}</td>
      <td>{{ result.score }} %</td>
      <td>{{ result.correct }}</td>
      <td>{{ result.incorrect }}</td>
    </tr>
  {% endfor %}

  </tbody>
</table>

    {% endblock content %}
</body>
</html>

questions/templates/questions/login.html
{% extends "base.html" %}

{% block content %}

    {% load crispy_forms_tags %}

    <!--Login-->
    <div class="p-3 mb-2 bg-success text-dark">
        <h1>Login</h1>
            <br>
        <form method="POST">
            {% csrf_token %}
            {{ login_form|crispy }}
        <br>
        <br>
            <button class="btn btn-outline-danger btn-lg" type="submit">Login</button>
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}

                </div>
            {% endif %}
        </form>
        <p class="text-center">Don't have an account? <a href="{% url 'questions:register' %}">Create an account</a>.
        </p>
    </div>

{% endblock %}

questions/templates/questions/main.html
{% extends 'base.html' %}
{% block content %}
    <h1>This is the films MAIN page</h1>
    <br>
    <h4>Some Pixar Movies:</h4>
    <ul>
        {% for number in '012'|make_list %}
            <li>Toy Story {{ forloop.counter }}</li>
        {% endfor %}
    </ul>
{% endblock %}

questions/templates/questions/quiz.html
{% extends "base.html" %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    {% block scripts %}
    {% endblock scripts %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container mt-3">
    {% block content %}
        <form method="post" action="{% url 'questions:validate_quiz' %}">
            {% csrf_token %}
            {% for question in questions %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ question.text }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Pick an answer:</h6>
                        <ul>
                            <input type="radio" id="{{ question.id }}" name="{{ question.id }}" value="0">
                            <label for="{{ question.0 }}">{{ question.0 }}</label><br>

                            <input type="radio" id="{{ question.id }}" name="{{ question.id }}" value="1">
                            <label for="{{ question.1 }}">{{ question.1 }}</label><br>

                            <input type="radio" id="{{ question.id }}" name="{{ question.id }}" value="2">
                            <label for="{{ question.2 }}">{{ question.2 }}</label><br>

                            <input type="radio" id="{{ question.id }}" name="{{ question.id }}" value="3">
                            <label for="{{ question.3 }}">{{ question.3 }}</label><br>
                        </ul>
                    </div>
                </div>
                <br>
            {% endfor %}
            <button  type="submit" type="button" class="btn btn-primary">Submit</button>
        </form>
    {% endblock content %}
</div>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</body>
</html>

questions/templates/questions/register.html
{% extends "base.html" %}

{% block content %}

    {% load crispy_forms_tags %}

    <!--Register-->
    <div class="p-3 mb-2 bg-success text-dark">
        <h1>Register</h1>
        <form method="POST">
            {% csrf_token %}
            {{ register_form|crispy }}
            <button class="btn btn-outline-danger btn-lg" type="submit">Register</button>
        </form>
        {% if message %}
            <div class="alert" role="alert">
                {{ message }}

            </div>
        {% endif %}

        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}

            </div>
        {% endif %}

    {% if register_form.errors %}
    <div class="alert alert-danger">
        {{ register_form.errors }}
    </div>
{% endif %}
        <p class="text-center">If you already have an account, <a href={% url 'questions:login' %}>login</a> instead.
        </p>
    </div>

{% endblock %}

questions/templates/questions/result.html
{% extends "base.html" %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    {% block scripts %}
    {% endblock scripts %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container mt-3">
    {% block content %}

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Your results</h5>
                <h6 class="card-subtitle mb-2 text-muted">Well done!</h6>
                <p class="card-text">Here's a breakdown of how you did</p>
                <div>
                    <table class="table">
                        <tbody>
                        <tr>
                            <td>Your score</td>
                            <td>{{ result.score }} %</td>
                        </tr>
                        <tr>
                            <td># Correct</td>
                            <td>{{ result.correct }}</td>
                        </tr>
                        <tr>
                            <td># Incorrect</td>
                            <td>{{ result.incorrect }}</td>
                        </tr>
                        <tr>
                            <td># Answered</td>
                            <td>{{ result.total_answered }}</td>
                        </tr>
                        <tr>
                            <td>Total # Questions</td>
                            <td>{{ result.total_questions }}</td>
                        </tr>

                        </tbody>
                    </table>
                </div>
                <a href="{% url 'questions:take_quiz' %}" class="card-link">Start another quiz</a>
                <a href="{% url 'questions:high_score' %}" class="card-link">See Highscores</a>
            </div>
        </div>
    {% endblock content %}
</div>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">#}
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap.min.css" %}">


    <!-- INSERT ADITIONAL INFORMATION TO THE HEAD TAG HERE-->
    {% block head %}
    {% endblock %}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
        <title>My Films App</title>
    {% endif %}

</head>
<body>
<!-- BOOTSTRAP NAVBAR CODE -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="d-flex justify-content-between px-5 mx-auto" style="width: 90%;">
        <span class="navbar-text text-white">TRIVIA QUIZZ APP</span>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link active" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link active" href="{% url 'questions:high_score' %}">HighScore</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link active" href="{% url 'questions:register' %}">Register</a>
            </li>

            {% if not user.is_authenticated %}
                <li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'questions:login' %}">LogIn</a>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'questions:logout' %}">LogOut</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<!-- END OF NAVBAR CODE-->


<div class="container-fluid mt-5" style="max-width: 80%">
    <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}

    <div class="p-3 mb-2 bg-success text-white rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold text-center">Test your knowledge with us!</h1>
                    <br>
        <p class="col-md-12 fs-2 text-center">Are you ready?!</p>
          <br>
          <br>
        <a type="button" class="d-grid gap-2 col-6 mx-auto btn btn-outline-danger btn-lg" href="{% url 'questions:take_quiz' %}">Take a quiz!</a>
      </div>
    </div>

{% endblock %}